minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
trustLockfile: false
blockExoticSubdeps: true
ignoreScripts: true
strictPeerDependencies: true
verifyStoreIntegrity: true
strictStorePkgContentCheck: true
overrides:
  brace-expansion: 5.0.9
  ip-address: 10.3.1
  "markdownlint-cli2>js-yaml": 5.2.2
  tar: 7.5.21
